USE books;
INSERT INTO books(book, price, rating) VALUES("A Light in the Attic","51.77","Three")
INSERT INTO books(book, price, rating) VALUES("Tipping the Velvet","53.74","One")
INSERT INTO books(book, price, rating) VALUES("Soumission","50.10","One")
INSERT INTO books(book, price, rating) VALUES("Sharp Objects","47.82","Four")
INSERT INTO books(book, price, rating) VALUES("Sapiens: A Brief History of Humankind","54.23","Five")
INSERT INTO books(book, price, rating) VALUES("The Requiem Red","22.65","One")
INSERT INTO books(book, price, rating) VALUES("The Dirty Little Secrets of Getting Your Dream Job","33.34","Four")
INSERT INTO books(book, price, rating) VALUES("The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull","17.93","Three")
INSERT INTO books(book, price, rating) VALUES("The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics","22.60","Four")
INSERT INTO books(book, price, rating) VALUES("The Black Maria","52.15","One")
INSERT INTO books(book, price, rating) VALUES("Starving Hearts (Triangular Trade Trilogy, #1)","13.99","Two")
INSERT INTO books(book, price, rating) VALUES("Shakespeare's Sonnets","20.66","Four")
INSERT INTO books(book, price, rating) VALUES("Set Me Free","17.46","Five")
INSERT INTO books(book, price, rating) VALUES("Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)","52.29","Five")
INSERT INTO books(book, price, rating) VALUES("Rip it Up and Start Again","35.02","Five")
INSERT INTO books(book, price, rating) VALUES("Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991","57.25","Three")
INSERT INTO books(book, price, rating) VALUES("Olio","23.88","One")
INSERT INTO books(book, price, rating) VALUES("Mesaerion: The Best Science Fiction Stories 1800-1849","37.59","One")
INSERT INTO books(book, price, rating) VALUES("Libertarianism for Beginners","51.33","Two") 
INSERT INTO books(book, price, rating) VALUES("It's Only the Himalayas","45.17","Two")
